services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5555:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  redis:
    image: redis:7-alpine
    ports:
      - "6333:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./apps/api/.env

  chat-service:
    build:
      context: .
      dockerfile: apps/chat-service/Dockerfile
    ports:
      - "50051:50051"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./apps/chat-service/.env

  notification-service:
    build:
      context: .
      dockerfile: apps/notification/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./apps/notification/.env

  ws-server:
    build:
      context: ./apps/ws-server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./apps/ws-server/.env

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
      ws-server:
        condition: service_started
    env_file:
      - ./apps/web/.env

volumes:
  postgres_data:
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
