// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at, is_channel, is_private
`

type CreateChannelParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.Name, arg.Description)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsChannel,
		&i.IsPrivate,
	)
	return i, err
}

const createChannelUser = `-- name: CreateChannelUser :exec
INSERT INTO channel_user (channel_id, user_id)
VALUES ($1, $2)
`

type CreateChannelUserParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateChannelUser(ctx context.Context, arg CreateChannelUserParams) error {
	_, err := q.db.ExecContext(ctx, createChannelUser, arg.ChannelID, arg.UserID)
	return err
}

const getAllChannels = `-- name: GetAllChannels :many
SELECT channels.id, channels.name, channels.description, channels.created_at, channels.updated_at, channels.is_channel, channels.is_private,json_agg(json_build_object(
'id', users.id,
'first_name', users.first_name,
'last_name', users.last_name,
'email', users.email)) AS users
FROM channels INNER JOIN channel_user
ON channels.id = channel_user.channel_id
INNER JOIN users ON channel_user.user_id = users.id
GROUP BY channels.id
`

type GetAllChannelsRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	IsChannel   bool            `json:"is_channel"`
	IsPrivate   bool            `json:"is_private"`
	Users       json.RawMessage `json:"users"`
}

func (q *Queries) GetAllChannels(ctx context.Context) ([]GetAllChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllChannelsRow
	for rows.Next() {
		var i GetAllChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsChannel,
			&i.IsPrivate,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT channels.id, channels.name, channels.description, channels.created_at, channels.updated_at, channels.is_channel, channels.is_private,json_agg(json_build_object(
'id', users.id,
'first_name', users.first_name,
'last_name', users.last_name,
'email', users.email)) AS users
FROM channels INNER JOIN channel_user
ON channels.id = channel_user.channel_id
INNER JOIN users ON channel_user.user_id = users.id
WHERE channels.id = $1
GROUP BY channels.id
`

type GetChannelByIDRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	IsChannel   bool            `json:"is_channel"`
	IsPrivate   bool            `json:"is_private"`
	Users       json.RawMessage `json:"users"`
}

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (GetChannelByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChannelByID, id)
	var i GetChannelByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsChannel,
		&i.IsPrivate,
		&i.Users,
	)
	return i, err
}

const getChannelsByName = `-- name: GetChannelsByName :many
SELECT channels.id, channels.name, channels.description, channels.created_at, channels.updated_at, channels.is_channel, channels.is_private,json_agg(json_build_object(
'id', users.id,
'first_name', users.first_name,
'last_name', users.last_name,
'email', users.email)) AS users
FROM channels INNER JOIN channel_user
ON channels.id = channel_user.channel_id
INNER JOIN users ON channel_user.user_id = users.id
WHERE channels.name ILIKE $1
GROUP BY channels.id
`

type GetChannelsByNameRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	IsChannel   bool            `json:"is_channel"`
	IsPrivate   bool            `json:"is_private"`
	Users       json.RawMessage `json:"users"`
}

func (q *Queries) GetChannelsByName(ctx context.Context, name string) ([]GetChannelsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelsByNameRow
	for rows.Next() {
		var i GetChannelsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsChannel,
			&i.IsPrivate,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelsByUserID = `-- name: GetChannelsByUserID :many
SELECT channels.id, channels.name, channels.description, channels.created_at, channels.updated_at, channels.is_channel, channels.is_private,json_agg(json_build_object(
'id', users.id,
'first_name', users.first_name,
'last_name', users.last_name,
'email', users.email
)) AS users
FROM channels
JOIN channel_user cu1 ON channels.id = cu1.channel_id
JOIN channel_user cu2 ON channels.id = cu2.channel_id
JOIN users ON cu2.user_id = users.id
WHERE cu1.user_id = $1
GROUP BY channels.id
`

type GetChannelsByUserIDRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	IsChannel   bool            `json:"is_channel"`
	IsPrivate   bool            `json:"is_private"`
	Users       json.RawMessage `json:"users"`
}

func (q *Queries) GetChannelsByUserID(ctx context.Context, userID uuid.UUID) ([]GetChannelsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelsByUserIDRow
	for rows.Next() {
		var i GetChannelsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsChannel,
			&i.IsPrivate,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientChannels = `-- name: GetClientChannels :many
SELECT channels.id FROM channels INNER JOIN channel_user
ON channels.id = channel_user.channel_id
WHERE channel_user.user_id = $1
`

func (q *Queries) GetClientChannels(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getClientChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinChannel = `-- name: JoinChannel :exec

INSERT INTO channel_user (channel_id, user_id)
VALUES ($1, $2)
`

type JoinChannelParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) JoinChannel(ctx context.Context, arg JoinChannelParams) error {
	_, err := q.db.ExecContext(ctx, joinChannel, arg.ChannelID, arg.UserID)
	return err
}
