// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateChannelParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.Name, arg.Description)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllChannels = `-- name: GetAllChannels :many
SELECT id, name, description, created_at, updated_at FROM channels
`

func (q *Queries) GetAllChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getAllChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, description, created_at, updated_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelsByUserID = `-- name: GetChannelsByUserID :many
SELECT channels.id, channels.name, channels.description, channels.created_at, channels.updated_at FROM channels INNER JOIN
channel_user ON channels.id = channel_user.channel_id
WHERE channel_user.user_id = $1
`

func (q *Queries) GetChannelsByUserID(ctx context.Context, userID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getChannelsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
