// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :exec

INSERT INTO messages (channel_id, user_id, message)
VALUES ($1, $2, $3)
`

type CreateMessageParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
	Message   string    `json:"message"`
}

// LIMIT 10;
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage, arg.ChannelID, arg.UserID, arg.Message)
	return err
}

const getChannelMessages = `-- name: GetChannelMessages :many
SELECT messages.id, messages.channel_id, messages.user_id, messages.message, messages.created_at, messages.updated_at,json_build_object(
'id', users.id,
'first_name', users.first_name,
'last_name', users.last_name,
'email', users.email,
'profile_picture', users.profile_picture
) AS from
FROM messages
INNER JOIN users ON messages.user_id = users.id
WHERE messages.channel_id = $1
ORDER BY messages.created_at ASC
`

type GetChannelMessagesRow struct {
	ID        uuid.UUID       `json:"id"`
	ChannelID uuid.UUID       `json:"channel_id"`
	UserID    uuid.UUID       `json:"user_id"`
	Message   string          `json:"message"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	From      json.RawMessage `json:"from"`
}

func (q *Queries) GetChannelMessages(ctx context.Context, channelID uuid.UUID) ([]GetChannelMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelMessages, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelMessagesRow
	for rows.Next() {
		var i GetChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.From,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
