// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getChannelMessages = `-- name: GetChannelMessages :many
SELECT messages.id, messages.channel_id, messages.user_id, messages.message, messages.created_at, messages.updated_at,users.first_name,users.last_name FROM messages INNER JOIN
users ON messages.user_id = users.id
WHERE messages.channel_id = $1
`

type GetChannelMessagesRow struct {
	ID        uuid.UUID `json:"id"`
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) GetChannelMessages(ctx context.Context, channelID uuid.UUID) ([]GetChannelMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelMessages, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelMessagesRow
	for rows.Next() {
		var i GetChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
