// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subscription.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :exec

INSERT INTO subscription(user_id,sub,endpoint)
VALUES($1,$2,$3)
`

type CreateSubscriptionParams struct {
	UserID   uuid.UUID       `json:"user_id"`
	Sub      json.RawMessage `json:"sub"`
	Endpoint string          `json:"endpoint"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createSubscription, arg.UserID, arg.Sub, arg.Endpoint)
	return err
}

const getUserSubscription = `-- name: GetUserSubscription :many

SELECT id, user_id, sub, endpoint, created_at, updated_at FROM subscription WHERE user_id=$1
`

func (q *Queries) GetUserSubscription(ctx context.Context, userID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubscription, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Sub,
			&i.Endpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unSubscribeUser = `-- name: UnSubscribeUser :exec

DELETE FROM subscription WHERE endpoint=$1 AND user_id=$2
`

type UnSubscribeUserParams struct {
	Endpoint string    `json:"endpoint"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) UnSubscribeUser(ctx context.Context, arg UnSubscribeUserParams) error {
	_, err := q.db.ExecContext(ctx, unSubscribeUser, arg.Endpoint, arg.UserID)
	return err
}
