// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createFiles = `-- name: CreateFiles :exec
INSERT INTO files(url,name,type,size,message_id)
VALUES ($1,$2,$3,$4,$5)
`

type CreateFilesParams struct {
	Url       string     `json:"url"`
	Name      string     `json:"name"`
	Type      string     `json:"type"`
	Size      int32      `json:"size"`
	MessageID *uuid.UUID `json:"message_id"`
}

func (q *Queries) CreateFiles(ctx context.Context, arg CreateFilesParams) error {
	_, err := q.db.ExecContext(ctx, createFiles,
		arg.Url,
		arg.Name,
		arg.Type,
		arg.Size,
		arg.MessageID,
	)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id,thread_id, user_id, message)
VALUES ($1, $2, $3 ,$4)
RETURNING id
`

type CreateMessageParams struct {
	ID       uuid.UUID `json:"id"`
	ThreadID uuid.UUID `json:"thread_id"`
	UserID   uuid.UUID `json:"user_id"`
	Message  string    `json:"message"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ThreadID,
		arg.UserID,
		arg.Message,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getChannelMessages = `-- name: GetChannelMessages :many
SELECT
  m.id, m.thread_id, m.user_id, m.message, m.created_at, m.updated_at,
  json_build_object(
    'id', u.id,
    'first_name', u.first_name,
    'last_name', u.last_name,
    'email', u.email,
    'profile_picture', u.profile_picture
  ) AS "from",
  COALESCE(
  json_arrayagg(
    json_build_object(
      'id', f.id,
      'url', f.url,
      'type', f.type,
      'size', f.size,
      'name',f.name
    )
    ORDER BY f.id
    ABSENT ON NULL
  ) FILTER (WHERE f.id IS NOT NULL),
  '[]'
  )::json
  AS files
FROM messages m
INNER JOIN users u ON m.user_id = u.id
LEFT JOIN files f ON f.message_id = m.id
WHERE m.thread_id = $1
GROUP BY m.id, u.id
ORDER BY m.created_at DESC
LIMIT $2
OFFSET $3
`

type GetChannelMessagesParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetChannelMessagesRow struct {
	ID        uuid.UUID       `json:"id"`
	ThreadID  uuid.UUID       `json:"thread_id"`
	UserID    uuid.UUID       `json:"user_id"`
	Message   string          `json:"message"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	From      json.RawMessage `json:"from"`
	Files     json.RawMessage `json:"files"`
}

func (q *Queries) GetChannelMessages(ctx context.Context, arg GetChannelMessagesParams) ([]GetChannelMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelMessages, arg.ThreadID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelMessagesRow
	for rows.Next() {
		var i GetChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.From,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadTotalMessages = `-- name: GetThreadTotalMessages :one

SELECT COUNT(*) FROM messages m WHERE m.thread_id=$1
`

func (q *Queries) GetThreadTotalMessages(ctx context.Context, threadID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getThreadTotalMessages, threadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
