// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: thread.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createDMThread = `-- name: CreateDMThread :one
INSERT INTO  thread (type)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateDMThread(ctx context.Context, type_ ThreadType) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createDMThread, type_)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createDMThreadUsers = `-- name: CreateDMThreadUsers :exec
INSERT INTO thread_user (thread_id, user_id)
VALUES ($1, $2),($1, $3)
`

type CreateDMThreadUsersParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) CreateDMThreadUsers(ctx context.Context, arg CreateDMThreadUsersParams) error {
	_, err := q.db.ExecContext(ctx, createDMThreadUsers, arg.ThreadID, arg.UserID, arg.UserID_2)
	return err
}

const createThread = `-- name: CreateThread :one
INSERT INTO thread (name, description, type)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateThreadParams struct {
	Name        *string    `json:"name"`
	Description *string    `json:"description"`
	Type        ThreadType `json:"type"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createThread, arg.Name, arg.Description, arg.Type)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createThreadUser = `-- name: CreateThreadUser :exec
INSERT INTO thread_user (thread_id, user_id)
VALUES ($1, $2)
`

type CreateThreadUserParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateThreadUser(ctx context.Context, arg CreateThreadUserParams) error {
	_, err := q.db.ExecContext(ctx, createThreadUser, arg.ThreadID, arg.UserID)
	return err
}

const getAllThreads = `-- name: GetAllThreads :many
SELECT  thread.id, thread.name, thread.description, thread.is_private, thread.type, thread.created_at, thread.updated_at,json_agg(json_build_object(
'id', users.id,
'first_name', users.first_name,
'last_name', users.last_name,
'profile_picture',users.profile_picture,
'email', users.email)) AS users
FROM thread INNER JOIN thread_user
ON thread.id = thread_user.thread_id
INNER JOIN users ON thread_user.user_id = users.id
GROUP BY  thread.id
`

type GetAllThreadsRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        *string         `json:"name"`
	Description *string         `json:"description"`
	IsPrivate   bool            `json:"is_private"`
	Type        ThreadType      `json:"type"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Users       json.RawMessage `json:"users"`
}

func (q *Queries) GetAllThreads(ctx context.Context) ([]GetAllThreadsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllThreads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllThreadsRow
	for rows.Next() {
		var i GetAllThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientThreads = `-- name: GetClientThreads :many
SELECT  thread.id FROM thread INNER JOIN thread_user
ON  thread.id = thread_user.thread_id
WHERE thread_user.user_id = $1
`

func (q *Queries) GetClientThreads(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getClientThreads, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDMThread = `-- name: GetDMThread :one
SELECT t.id, t.type
FROM  thread t
JOIN thread_user tu1 ON t.id = tu1.thread_id
JOIN thread_user tu2 ON t.id = tu2.thread_id
WHERE t.type = 'dm'
  AND tu1.user_id = $1
  AND tu2.user_id = $2
GROUP BY t.id
`

type GetDMThreadParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

type GetDMThreadRow struct {
	ID   uuid.UUID  `json:"id"`
	Type ThreadType `json:"type"`
}

func (q *Queries) GetDMThread(ctx context.Context, arg GetDMThreadParams) (GetDMThreadRow, error) {
	row := q.db.QueryRowContext(ctx, getDMThread, arg.UserID, arg.UserID_2)
	var i GetDMThreadRow
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const getThreadAndUser = `-- name: GetThreadAndUser :many

SELECT t.id,t.name,'group' as type FROM  thread t WHERE t.name ILIKE $1 AND t.is_private=false
UNION
SELECT DISTINCT u.id,CONCAT(u.first_name,' ',u.last_name) as name,'user' as type FROM users u
WHERE u.first_name ILIKE $1 OR u.last_name ILIKE $1
`

type GetThreadAndUserRow struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
	Type string    `json:"type"`
}

func (q *Queries) GetThreadAndUser(ctx context.Context, name *string) ([]GetThreadAndUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getThreadAndUser, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreadAndUserRow
	for rows.Next() {
		var i GetThreadAndUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadByID = `-- name: GetThreadByID :one
SELECT  thread.id, thread.name, thread.description, thread.is_private, thread.type, thread.created_at, thread.updated_at,json_agg(json_build_object(
'id', users.id,
'first_name', users.first_name,
'last_name', users.last_name,
'profile_picture',users.profile_picture,
'email', users.email)) AS users
FROM thread INNER JOIN thread_user
ON thread.id = thread_user.thread_id
INNER JOIN users ON thread_user.user_id = users.id
WHERE  thread.id = $1
GROUP BY thread.id
`

type GetThreadByIDRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        *string         `json:"name"`
	Description *string         `json:"description"`
	IsPrivate   bool            `json:"is_private"`
	Type        ThreadType      `json:"type"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Users       json.RawMessage `json:"users"`
}

func (q *Queries) GetThreadByID(ctx context.Context, id uuid.UUID) (GetThreadByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getThreadByID, id)
	var i GetThreadByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Users,
	)
	return i, err
}

const getThreadUsers = `-- name: GetThreadUsers :many

SELECT u.id FROM users u
JOIN thread_user tu ON tu.user_id =u.id
JOIN thread t ON t.id=tu.thread_id
WHERE t.id=$1
`

func (q *Queries) GetThreadUsers(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getThreadUsers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadsByUserID = `-- name: GetThreadsByUserID :many
SELECT
    thread.id, thread.name, thread.description, thread.is_private, thread.type, thread.created_at, thread.updated_at,
    json_agg(json_build_object(
        'id', users.id,
        'first_name', users.first_name,
        'last_name', users.last_name,
        'email', users.email,
        'profile_picture', users.profile_picture
    )) AS users,
    COALESCE(
        (
            SELECT json_build_object(
                'id', m.id,
                'message', m.message,
                'user_id', m.user_id,
                'created_at', m.created_at
            )
            FROM messages m
            WHERE m.thread_id = thread.id
            ORDER BY m.created_at DESC
            LIMIT 1
        ),
        'null'
    )::json AS last_message
FROM thread
JOIN thread_user cu1 ON thread.id = cu1.thread_id
JOIN thread_user cu2 ON thread.id = cu2.thread_id
JOIN users ON cu2.user_id = users.id
WHERE cu1.user_id = $1
GROUP BY thread.id
`

type GetThreadsByUserIDRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        *string         `json:"name"`
	Description *string         `json:"description"`
	IsPrivate   bool            `json:"is_private"`
	Type        ThreadType      `json:"type"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Users       json.RawMessage `json:"users"`
	LastMessage json.RawMessage `json:"last_message"`
}

func (q *Queries) GetThreadsByUserID(ctx context.Context, userID uuid.UUID) ([]GetThreadsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getThreadsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreadsByUserIDRow
	for rows.Next() {
		var i GetThreadsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
			&i.LastMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnReadChatsByUserID = `-- name: GetUnReadChatsByUserID :many
SELECT
  l.last_read_message_id AS last_read,
  l.thread_id,
  (
    SELECT COUNT(m.id)
    FROM messages m
    WHERE
      m.thread_id = l.thread_id
      AND m.user_id != $1
     AND m.created_at > lm.created_at

  ) AS unread_count
FROM last_read l
JOIN messages lm ON l.last_read_message_id = lm.id
WHERE l.user_id = $1
`

type GetUnReadChatsByUserIDRow struct {
	LastRead    uuid.UUID `json:"last_read"`
	ThreadID    uuid.UUID `json:"thread_id"`
	UnreadCount int64     `json:"unread_count"`
}

func (q *Queries) GetUnReadChatsByUserID(ctx context.Context, userID uuid.UUID) ([]GetUnReadChatsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnReadChatsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnReadChatsByUserIDRow
	for rows.Next() {
		var i GetUnReadChatsByUserIDRow
		if err := rows.Scan(&i.LastRead, &i.ThreadID, &i.UnreadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinThread = `-- name: JoinThread :exec

INSERT INTO thread_user (thread_id, user_id)
VALUES ($1, $2)
`

type JoinThreadParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) JoinThread(ctx context.Context, arg JoinThreadParams) error {
	_, err := q.db.ExecContext(ctx, joinThread, arg.ThreadID, arg.UserID)
	return err
}

const upsertLastRead = `-- name: UpsertLastRead :exec

INSERT INTO last_read(thread_id,last_read_message_id,user_id)
VALUES($1,$2,$3) ON CONFLICT(user_id,thread_id)
DO UPDATE SET last_read_message_id = EXCLUDED.last_read_message_id,updated_at=now()
`

type UpsertLastReadParams struct {
	ThreadID          uuid.UUID `json:"thread_id"`
	LastReadMessageID uuid.UUID `json:"last_read_message_id"`
	UserID            uuid.UUID `json:"user_id"`
}

func (q *Queries) UpsertLastRead(ctx context.Context, arg UpsertLastReadParams) error {
	_, err := q.db.ExecContext(ctx, upsertLastRead, arg.ThreadID, arg.LastReadMessageID, arg.UserID)
	return err
}
