name: Pulumi Pull Request
on:
  pull_request:
    paths:
      - 'infra/**'
permissions:
  id-token: write
  contents: read
  pull-requests: write 
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - uses: pnpm/action-setup@v4
      - name: Inject ESC environment variables
        uses: pulumi/esc-action@v1
        with:
          environment: ${{ vars.ORG_NAME }}/thread/prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - run: pnpm install
        working-directory: infra
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: ${{ vars.ORG_NAME }}/thread
          comment-on-pr: true
          work-dir: infra
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
