name: Pulumi Up
on:
  push:
    paths:
      - "infra/**"
    branches:
      - main
jobs:
  update:
    permissions:
      id-token: write
      contents: read
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v4
        
      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: ${{ vars.ORG_NAME }}
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:shemaikuzwe
      - name: Inject ESC environment variables
        uses: pulumi/esc-action@v1
        with:
          environment: ${{ vars.ORG_NAME }}/thread/prod
      - run: pnpm install
        working-directory: infra
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ vars.ORG_NAME }}/thread
          work_dir: infra
